=== creighton/statement-schema/test/schemas/statement.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "JSON Schema for the base properties of an xAPI Statement",
    "id":"http://localhost:8080/statements-schema.json",

    "type": "object",

    "required": ["actor", "verb", "object"],

    "additionalProperties": false,

    "properties": {
        "id": { "type": "string" },
        "actor": { "type": "object" },
        "verb" : { "type": "object" },
        "object": { "type": "object" },
        "result": { "type": "object"},
        "context": { "type": "object" },
        "timestamp": { "type": "string" },
        "stored": { "type": "string" },
        "authority": { "type": "object" },
        "version": { "type": "string" },
        "attachments": { "type": "array" }
    }
}

=== creighton/statement-schema/test/statements/attachment/attachment-full.json
{
    "actor":{"mbox":"mailto:tom@example.com", "name":"andy", "objectType":"Agent"},
    "verb":{"id":"http://tom.com/verb", "display":{"en":"hi"}},
    "object": {"id":"http://tom.com/obj"},
    "attachments": [
        {
            "usageType": "http://adlnet.gov/expapi/attachments/test",
            "display": { "en-US": "Test" },
            "description": { "en-US": "A test" },
            "contentType": "application/octet-stream",
            "length": 4235,
            "sha2": "672fa5fa658017f1b72d65036f13379c6ab05d4ab3b6664908d8acf0b6a0c634",
            "fileUrl": "http://server/path/file.txt"
        }
    ]
}

=== creighton/statement-schema/test/statements/various.json
{
    "id":"cc8937ed-3151-1659-b377-38ed4fc96c90",
    "actor":{"mbox":"mailto:tom@example.com", "name":"andy", "objectType":"Agent"},
    "verb":{"id":"http://tom.com/verb", "display":{"en":"hi"}},
    "object": {"id":"fox://tomcom/obj"},
    "version":"1.0.3",
    "timestamp":"2017-03-23T21:14:21.690Z",
    "stored":"1971-01-27T22:44:32.458999Z"
}

=== creighton/statement-schema/test/statements/authority/auth-agent.json
{
    "actor":{"mbox":"mailto:tom@example.com", "name":"andy", "objectType":"Agent"},
    "verb":{"id":"http://tom.com/verb", "display":{"en":"hi"}},
    "object": {"id":"http://tom.com/obj"},
    "authority": {
    	"objectType" : "Agent",
		"account": {
			"homePage":"http://example.com/xAPI/OAuth/Token",
		    "name":"oauth_consumer_x75db"
    	}
    }
}

=== creighton/statement-schema/test/statements/context/context-empty-objects.json
{
    "id":"f5070c3a-cd39-4dc3-8dd2-4ad3b511c407",
    "actor":{"mbox":"mailto:tom@example.com", "name":"andy", "objectType":"Agent"},
    "verb":{"id":"http://tom.com/verb", "display":{"en":"hi"}},
    "object": {"id":"http://tom.com/obj"},
    "context": {
        "registration": "bc5ca8ec-b130-4d8e-a092-3af748cf7a54",
        "revision":"4",
        "platform":"yep",
        "language":"en",
        "contextActivities": {},
        "extensions": {}
    }
}
